# Generated by Django 4.0.3 on 2022-08-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AIC_APP', '0001_initial'),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.SlugField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('name', models.TextField(default='Public Api', max_length=255)),
                ('api_key_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_framework_api_key.apikey', unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIC_APP.yobotuser')),
            ],
            options={
                'db_table': 'AIC_API',
            },
        ),
    ]
