# Generated by Django 3.2.5 on 2022-08-08 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('AIC_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='id',
        ),
        migrations.AlterField(
            model_name='api',
            name='api_key_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rest_framework_api_key.apikey'),
        ),
    ]
