# Generated by Django 3.2.5 on 2022-07-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIC_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='name',
            field=models.TextField(default='Public Api', max_length=255),
        ),
    ]
