# Generated by Django 4.0.5 on 2022-08-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yobotuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=50)),
                ('PhoneNum', models.IntegerField(default=0)),
                ('ChatBotName', models.CharField(default='', max_length=50)),
                ('APIKEY', models.SlugField(default='', max_length=200)),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
