# Generated by Django 4.0.3 on 2022-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIC_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yobotuser',
            name='improvedata',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
