# Generated by Django 4.0.3 on 2022-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIC_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_ans',
            name='questions',
            field=models.TextField(max_length=255, null=True, unique=True),
        ),
    ]
