# Generated by Django 4.0.3 on 2022-08-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIC_APP', '0002_yobotuser_improvedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='yobotuser',
            name='errmsg',
            field=models.CharField(default='Sorry, for more details refer our site. ', max_length=300),
        ),
        migrations.AddField(
            model_name='yobotuser',
            name='greetmsg',
            field=models.CharField(default='Welcome, How can i help you', max_length=100),
        ),
    ]
