# Generated by Django 4.0.3 on 2022-07-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIC_APP', '0003_yobotuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='yobotuser',
            name='APIKEY',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
